# yaml-language-server: $schema=https://azuremlsdk2.blob.core.windows.net/latest/onlineEndpoint.schema.json
name: dabrady-managed
type: online
infrastructure: managed
auth_mode: aml_token
traffic:
  prod: 100

deployments:
  #prod deployment
  prod:    
    model: azureml:mnist-dabrady-model:1  # should replace this in the pipeline
    code_configuration:
      code: 
        directory: ./onlinescoring/
      scoring_script: score.py
    environment: 
        name: model-1-env-dabrady
        version: 1
        path: .
        conda_file: config/tf_conda.yml
    sku: Standard_F2s_v2
    scale_settings:
      scale_type: manual
      instance_count: 1
      min_instances: 1
      max_instances: 2