name: cli-e2etest

on: 
  push:
    branches:
      - main
  workflow_dispatch:
        
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: |
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.11-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - run: az ml -h
    - run: az ml job -h
    - run: az ml data -h
    - run: az ml datastore -h
    - run: az ml model -h
    - run: az ml environment -h
    - run: az ml endpoint -h
    - run: az ml compute -h
    - run: az ml workspace -h
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - run: |
          az config set defaults.workspace=e2edemos
          az config set defaults.group=demorg
          az account set -s 92c76a2f-0e1c-4216-b65e-abf7a3f34c1e
    - run: |
          az ml environment create --file examples/train/tensorflow/mnist/tf_env.yml
    - run: |
          # az ml data create --file examples/iris/iris-data.yml
    - run: |
          az ml job create --file examples/train/tensorflow/tf_mnist_job.yml --name tf_mnist_dabrady_$GITHUB_RUN_ID --query metadata.interaction_endpoints.studio
    - run: |
          # az ml model create --file examples/deploy/sklearn/simplemodel.yml -n modeltest_$GITHUB_RUN_ID