name: cli-e2etest

on: 
  push:
    branches:
      - main
  workflow_dispatch:
        
jobs:
  dev-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.7
    - run: |
        az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.21-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_TOKEN}}
    - name: set az defaults
      run: |
          az config set defaults.workspace=dabrady-aml-workspace
          az config set defaults.group=aml-rg
          az account set -s bc202ec2-54ef-4576-b7fb-a961c983398e
    - name: Create an environment
      run: |
          az ml environment create --file examples/train/tensorflow/mnist/tf_env.yml
    - name: Create a job
      run: |
          az ml job create --file examples/train/tensorflow/mnist/tf_mnist_job.yml --name tf_mnist_dabrady_$GITHUB_RUN_ID --set command="python train.py ${{ secrets.ACTIONS_TOKEN }}" --query metadata.interaction_endpoints.studio